routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('pages.home');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('/landads','LandadsController');
Route::resource('/livestockads','LivestockadsController');
Route::resource('/searchlivestocks', 'SearchlivestockController');
Route::resource('/searchland', 'SearchlandController');
Route::get('/livestockads/{id}/edit/delete_image/{galleryid}','LivestockadsController@delete_image');
Route::get('/landads/{id}/edit/delete_image/{galleryid}','LandadsController@delete_image');
Route::resource('/users','UserController');
Route::get('/forgetpassword', 'ForgetpasswordController@index');
Route::post('/forgetpassword/send_password', 'ForgetpasswordController@send_password');

//Route::resource('/forgetpass','ForgetpasswordController');
//Route::get('/subscription/{user_id}', 'SubscriptionController@subscription');
//Route::get('/edit/{user_id}', 'UserController@edit');
//Route::get('editprofile', 'ProfileController@edit')->name('editprofile');
// Route::get('editprofile', function() {
//     return view('pages.editprofile');
// })->name('editprofile');

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'hdpwd', 'phone', 'address_line_1', 'address_line_2', 'zipcode', 'description', 'user_type', 'profile_picture',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'hdpwd', 'zipcode', 'remember_token',
    ];
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\User;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Validator;
use App\Http\Requests;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Input;
use Auth;
use Session;
use DB;
use Hash;
use Image;
use App\Classes\ErrorsClass;

class UserController extends Controller
{    

    public function __construct()
    {
        $this->middleware('auth');
    }

     public function index(Request $request)

    {
          

    }
    
     public function create()

    {


    }
    
        public function store(Request $request)

    {

    }
    
        public function show($id)

    {

        
    }
    
        public function edit($id)

    {
        $user = User::find($id);
        return view('users.edit', compact('user'));

    }
    
   public function update(Request $request, $id)

    {

        $user = User::findOrFail($id); 
      
        $name = $request->name;
        $email = $request->email;
        $phone = $request->phone;
        $address_line_1 = $request->address_line_1;
        $address_line_2 = $request->address_line_2;
        $description = $request->description;
        $updated_by = $id;

        $input = $request->only(['name', 'email', 'phone', 'address_line_1', 'address_line_2', 'description','updated_by']); 

        $updated =  $user->fill($input)->save();

        $file = $_FILES['profile_picture']['name'];

        if($file!=''){

          $file = Input::file('profile_picture')->getFilename();
          $thumbnail_path = public_path('uploads/propic/thumbnail/');
          $original_path = public_path('uploads/propic/original/');
          $file_name = 'user_'. $user->id .'_'. time() . '.' . Input::file('profile_picture')->getClientOriginalExtension();
          
            Image::make(Input::file('profile_picture')->getRealPath())
                  ->resize(261,null,function ($constraint) {
                    $constraint->aspectRatio();
                     })
                  ->save($original_path . $file_name)
                  ->resize(90, 90)
                  ->save($thumbnail_path . $file_name);

            $user->update(['profile_picture' => $file_name]);

          } 
       
        if($updated) {

            if($user->user_type == 'live_stock_owner') {
                return redirect()->route('livestockads.index')

                ->with('success','User successfully edited!');
            } else {
                return redirect()->route('landads.index')

                ->with('success','User successfully edited!');
            }

        } else {

          if($user->user_type == 'live_stock_owner') {
                return redirect()->route('livestockads.index')

                ->with('error','Woops Something is wrong!');
            } else {
                return redirect()->route('landads.index')

                ->with('error','Woops Something is wrong!');
            }

         /*return redirect()->route('users.index')
                ->with('error','Woops Something is wrong!');    
            */
        }

    }
       
}

resources/views/users/edit.blade.php
@extends('layouts.default')

@section('title', 'Drop Baa')

@section('content')

        <div class="col-sm-8 col-sm-offset-2 formarea edit_profile_section_user">
          <h1>Edit Your Profile</h1>
          <div class="white_bg">
          <div class="row">
          <div class="col-sm-6 col-xs-6 leftborder">
            <hr class="borderline">
          </div>
          <div class="col-sm-6 col-xs-6 rightborder">
            <hr class="borderline">
          </div>
        </div>
        <div class="registeration_section formsection">
          <form class="registerform" id="registerform" action="{{ route('users.update', $user->id) }}" method="POST" enctype="multipart/form-data">
          
           {{ csrf_field() }}          

          {{ method_field('PUT') }}
            <div class="row">
              <div class="col-sm-12 form-group forminput">
                <label>Your Name</label>
                <input type="text" class="form-control" id="name" placeholder="Enter Your Full Name" value="{{ $user->name }}" name="name">
              </div>
            </div>
            <div class="row">
              <div class="col-sm-12 form-group forminput">
                <label>Email Address</label>
                <input type="email" class="form-control" id="email" placeholder="Enter Your Email" value="{{ $user->email }}" name="email" readonly="">
              </div>
            </div>
            <div class="row">
              <div class="col-sm-12 form-group forminput">
                 <label>Phone Number</label>
                <input type="text" class="form-control" id="phone" placeholder="Your phone Number" value="{{ $user->phone }}" name="phone">
              </div>
            </div>
           
           <div class="row">
              <div class="col-sm-12 form-group forminput">
                <label>Address First Line</label>
                <input type="text" class="form-control" id="address_line_1" placeholder="Address First Line" value="{{ $user->address_line_1 }}" name="address_line_1">
              </div>
            </div>
            <div class="row">
              <div class="col-sm-12 form-group forminput">
                <label>Address Second Line</label>
                <input type="text" class="form-control" id="address_line_2" placeholder="Address Second Line" value="{{ $user->address_line_2 }}" name="address_line_2">
              </div>
            </div>
             <div class="row">
              <div class="col-sm-12 form-group forminput">
                <label>Description</label>
                <textarea class="form-control" name="description" rows="3" placeholder="Write About Yourself" maxlength="200" minlength="50">{{ $user->description }}</textarea>
              </div>
            </div>
            <!--  <div class="row">
              <div class="col-sm-12 form-group forminput">
                <label>Choose Option</label>
                <div class="col-sm-12 radiobtns nopadding">
                  <label class="radiobutton radio-inline">I have livestock
                  <input type="radio" name="radio" >
                  <span class="checkmark"></span>
                  </label>
                  <label class="radiobutton radio-inline">I have land
                  <input type="radio" name="radio">
                  <span class="checkmark"></span>
                  </label>
                </div>
              </div>
            </div> -->
            <div class="row">
              <div class="col-sm-12 form-group forminput">
                <label>Upload Your Profile Image</label>
                <div class="col-sm-2 col-xs-3 browseimage nopadding" id="browse_img">
                  @if($user->profile_picture!='')
                    <img src="{{ url('/public') }}/uploads/propic/thumbnail/{{$user->profile_picture}}" class="img-responsive">
                  @else
                    <img src="{{ url('/public') }}/images/dummy.jpg" class="img-responsive">
                  @endif
                </div>
                <div class="col-sm-10 col-xs-9">
                <input type="file" id="profile_picture" name="profile_picture" accept="image/*" style="display: none;">
                <div class="browse_btn" id="browsebtn">
                  <span>Browse Image</span>
                  <p>No File Selected</p>
                </div>
              </div>
              </div>
            </div>
            <div class="savebnt text-right">
              <button type="submit" class="btn btn-default">Save</button>
            </div>
          </form>
        </div>
      </div>
      </div>
    </div>
    <style>
      body {
    background: rgba(0, 0, 0, 0) url("{{ url('/public') }}/images/bg-img.jpg") no-repeat scroll center center / cover  ;
    
    height: 100vh;
}
    </style>
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<!--     <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script> -->
    <!-- Include all compiled plugins (below), or include individual files as needed -->
 <!--    <script src="js/bootstrap.min.js"></script> -->
  </body>
</html>
<script>
 $(document).ready(function() {
 
            jQuery('#browsebtn').on('click', function() {
                 jQuery('#profile_picture').click();
            });
            jQuery("#profile_picture").change(function() {
                 var file = this.files[0];
                 var imagefile = file.type;
                 var imageTypes= ["image/jpeg","image/png","image/jpg"];
                if(imageTypes.indexOf(imagefile) == -1)
                 {
                      jQuery("#browse_img").html("<span class='msg-error'>Please Select A valid Image File</span><br /><span>Only jpeg, jpg and png Images type allowed</span>");
                      return false;
                 } else {
                 var reader = new FileReader();
                 reader.onload = function(e){
                    jQuery("#browse_img").html('<img src="' + e.target.result + '"  />');        
                 };
                  reader.readAsDataURL(this.files[0]);
                }
            });


  $.validator.addMethod("alphaLetterNumber", function(value, element) {
     return this.optional(element) || value == value.match(/^[a-zA-Z0-9]+$/) && value.match(/[a-zA-Z0-9]/);
    });

     $.validator.addMethod("alphaLetterNumberSpace", function(value, element) {
     return this.optional(element) || value == value.match(/^[ a-zA-Z0-9]+$/) && value.match(/[a-zA-Z0-9]/);
    });

    $.validator.addMethod("alphaLetter", function(value, element) {
     return this.optional(element) || value == value.match(/^[ a-zA-Z]+$/) && value.match(/[a-zA-Z]/);
    });

    $("#registerform").validate({
        rules: {
                name: {
                    required: true,
                    alphaLetter: true,
                    minlength: 2,
                    maxlength: 60
                },
               phone: {
                   required: true,
                   number: true,
                   minlength: 10,
                   maxlength: 12
               },
               address_line_1: {
                   required: true,
                   maxlength: 250
               }
               /*user_type: {
                   required: true
               }*/
            },
        messages: {
              name: {
                  required: "Please enter name.",
                  alphaLetter: "Please enter a valid name.",
                  minlength: "Minimum 2 characters required.",
                  maxlength: "Maximum 60 characters allowed."
                },
              phone: {
                  required: "Please enter number.",
                  number: "Please enter a valid number.",
                  minlength: "Minimum 10 characters required.",
                  maxlength: "Maximum 12 characters allowed."
                  },
              address_line_1: {
                  required: "Please enter address.",
                  maxlength: "Maximum 250 characters allowed."
                }
                /*user_type: {
                  required: "Please choose option."
                }*/
            },
        submitHandler: function(form) {
            form.submit();
          }
        });

 });
    </script>

      @stop

resources/views/users/index.blade.php
@extends('layouts.default')

@section('title', 'WineBaa')

@section('content')

<section id="posts" class="parallax-section">

<div class="container">
        <div class="row">
       
           <div class="row">

        <div class="col-lg-12 margin-tb">

            <div class="pull-left">

                <h2>Posts</h2>

            </div>

            <div class="pull-right">

                <a class="btn btn-success" href="{{ route('posts.create') }}"> Create New Post</a>

            </div>

        </div>

    </div>


    @if ($message = Session::get('success'))

        <div class="alert alert-success">

            <p>{{ $message }}</p>

        </div>

    @endif


    <table class="table table-bordered">

        <tr>

            <th>No</th>

            <th>Title</th>

            <th>Description</th>
            
             <th>Image</th>

            <th width="280px">Action</th>

        </tr>

    @foreach ($livestockads as $key => $post)

    <tr>

        <td>{{ ++$i }}</td>

        <td>{{ $post->lst_ad_title }}</td>

        <td>{{ $post->lst_description }}</td>
        
         <td><img src="{{ url('public/uploads/postsimages/'.$post->lst_pictures) }}" width="100" height="60" /></td>

        <td>

            <a class="btn btn-info" href="{{ route('livestockads.show',$post->id) }}">Show</a>

            <a class="btn btn-primary" href="{{ route('livestockads.edit',$post->id) }}">Edit</a>

            {!! Form::open(['method' => 'DELETE','route' => ['livestockads.destroy', $post->id],'style'=>'display:inline']) !!}

            {!! Form::submit('Delete', ['class' => 'btn btn-danger']) !!}

            {!! Form::close() !!}

        </td>

    </tr>

    @endforeach

    </table>


    {!! $livestockads->render() !!} 
            
        
        </div>
      </div>
		
		</section>
<style>
      body {
    background: rgba(0, 0, 0, 0) url("{{ url('/public') }}/images/bg-img.jpg") no-repeat scroll center center / cover  ;
    height: 100vh;
}
    </style>
  @stop