routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('pages.home');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('/landads','LandadsController');
Route::resource('/livestockads','LivestockadsController');
Route::resource('/searchlivestocks', 'SearchlivestockController');
Route::resource('/searchland', 'SearchlandController');
Route::get('/livestockads/{id}/edit/delete_image/{galleryid}','LivestockadsController@delete_image');
Route::get('/landads/{id}/edit/delete_image/{galleryid}','LandadsController@delete_image');
Route::resource('/users','UserController');
Route::get('/forgetpassword', 'ForgetpasswordController@index');
Route::post('/forgetpassword/send_password', 'ForgetpasswordController@send_password');

//Route::resource('/forgetpass','ForgetpasswordController');
//Route::get('/subscription/{user_id}', 'SubscriptionController@subscription');
//Route::get('/edit/{user_id}', 'UserController@edit');
//Route::get('editprofile', 'ProfileController@edit')->name('editprofile');
// Route::get('editprofile', function() {
//     return view('pages.editprofile');
// })->name('editprofile');

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                <div class="navbar-header">

                    <!-- Collapsed Hamburger -->
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse">
                        <span class="sr-only">Toggle Navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                    <!-- Branding Image -->
                    <a class="navbar-brand" href="{{ url('/') }}">
                        {{ config('app.name', 'Laravel') }}
                    </a>
                </div>

                <div class="collapse navbar-collapse" id="app-navbar-collapse">
                    <!-- Left Side Of Navbar -->
                    <ul class="nav navbar-nav">
                        &nbsp;
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="nav navbar-nav navbar-right">
                        <!-- Authentication Links -->
                        @if (Auth::guest())
                            <li><a href="{{ route('login') }}">Login</a></li>
                            <li><a href="{{ route('register') }}">Register</a></li>
                        @else
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <ul class="dropdown-menu" role="menu">
                                    <li>
                                        <a href="{{ route('logout') }}"
                                            onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                            Logout
                                        </a>

                                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                            {{ csrf_field() }}
                                        </form>
                                    </li>
                                </ul>
                            </li>
                        @endif
                    </ul>
                </div>
            </div>
        </nav>

        @yield('content')
    </div>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}"></script>
</body>
</html>

resources/views/layouts/default.blade.php
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>@yield('title')</title>
    <link rel="shortcut icon" href="{{ url('/public') }}/favicon.ico" type="image/x-icon">
    <!-- Bootstrap -->
    <link href="{{ url('/public') }}/css/bootstrap.min.css" rel="stylesheet">
    <link href="{{ url('/public') }}/css/style.css" rel="stylesheet">
    <link href="{{ url('/public') }}/css/responsive.css" rel="stylesheet">
    <link href="{{ url('/public') }}/font-awesome/css/font-awesome.min.css" rel="stylesheet">
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <script src="{{ url('/public') }}/js/jquery.min.js"></script>
    <script src="{{ url('/public') }}/js/jquery.validate.min.js"></script>
    <script src="{{ url('/public') }}/js/jquery-validate.bootstrap-tooltip.min.js"></script>
    <script src="{{ url('/public') }}/js/bootstrap.min.js"></script>

  </head>
  <body>
  
  <div class="bg_img">

  @include('layouts.header')

  @yield('content')

  @include('layouts.footer')
   
   </div>
  </body>
</html>

resources/views/layouts/default2.blade.php
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>@yield('title')</title>
    <!-- Bootstrap -->
    <link href="{{ url('/public') }}/css/bootstrap.min.css" rel="stylesheet">
    <link href="{{ url('/public') }}/css/style.css" rel="stylesheet">
    <link href="{{ url('/public') }}/css/responsive.css" rel="stylesheet">
    <link href="{{ url('/public') }}/font-awesome/css/font-awesome.min.css" rel="stylesheet">
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <script src="{{ url('/public') }}/js/jquery.min.js"></script>
    <script src="{{ url('/public') }}/js/jquery.validate.min.js"></script>
    <script src="{{ url('/public') }}/js/jquery-validate.bootstrap-tooltip.min.js"></script>
    <script src="{{ url('/public') }}/js/bootstrap.min.js"></script>

  </head>
  <body>

  @include('layouts.header2')

  @yield('content')

  @include('layouts.footer')

  </body>
</html>

resources/views/layouts/flash-message.blade.php
@if ($message = Session::get('success'))

<div class="alert alert-success alert-block">

	<button type="button" class="close" data-dismiss="alert">×</button>	

        <strong>{{ $message }}</strong>

</div>

@endif


@if ($message = Session::get('error'))

<div class="alert alert-danger alert-block">

	<button type="button" class="close" data-dismiss="alert">×</button>	

        <strong>{{ $message }}</strong>

</div>

@endif


@if ($message = Session::get('warning'))

<div class="alert alert-warning alert-block">

	<button type="button" class="close" data-dismiss="alert">×</button>	

	<strong>{{ $message }}</strong>

</div>

@endif


@if ($message = Session::get('info'))

<div class="alert alert-info alert-block">

	<button type="button" class="close" data-dismiss="alert">×</button>	

	<strong>{{ $message }}</strong>

</div>

@endif


@if ($errors->any())

<div class="alert alert-danger">

	<button type="button" class="close" data-dismiss="alert">×</button>	

	Please check the form below for errors

</div>

@endif

resources/views/layouts/footer.blade.php
<!-- <div class="container copyright_footer_setion">
<div class="col-sm-12 copyright_setion">
   <div class="copyright_text">
        <p class="copy_right_text">© 2018 Copyright <a href="{{url('dropbaa')}}">Drop Baa</a>.All Rights Reserved</p>
   <div>
</div>
</div> -->

resources/views/layouts/header.blade.php
        @if(Auth::check())
        <?php
        $user = Auth::user();    
        $user_id =  Auth::id(); 
        ?>
        <!--header-after-login-->
        <header class="after_login">
            <!-- <div class="container-fluid"> -->
            <div class="container">
                <div class="col-sm-4 col-xs-4 logo_img">
                    <a href="{{ url('/') }}"><img src="{{ url('/public') }}/images/logo.png" class="img-responsive"></a>
                </div>
                <div class="col-sm-8 col-xs-8 userimg text-right">
                  <div class="col-sm-8">
                <ul class="before_login_menu">
                        <li class="menu_link"><a href="{{ route('searchlivestocks.index') }}">Livestockads</a></li>
                        <li class="menu_link"><a href="{{ route('searchland.index') }}">Landads</a></li>
                </ul>
                </div>
               <div class="col-sm-4">
                    <div class="dropdown menu_after_login">
                    @if($user->profile_picture!='')
                        <button class="btn btn-primary dropdown-toggle dropdown_menu" type="button" data-toggle="dropdown"><span class="user_name_title">Welcome, {{ Auth::user()->name }}</span><img src="{{ url('/public') }}/uploads/propic/thumbnail/{{ $user->profile_picture }}" class="img-circle">
                        <i class="fa fa-caret-down"></i></button>
                    @else
                    <button class="btn btn-primary dropdown-toggle dropdown_menu" type="button" data-toggle="dropdown"><span class="user_name_title">Welcome, {{ Auth::user()->name }}</span><img src="{{ url('/public') }}/images/dummy.jpg" class="img-circle">
                    <i class="fa fa-caret-down"></i></button>
                    @endif
                        <ul class="dropdown-menu dropdown_menu_list">
                                  @if($user->user_type == 'live_stock_owner' ) 
                                  <li><a href="{{ route('livestockads.index') }}">{{ Auth::user()->name }}</a></li>
                                  @else
                                  <li><a href="{{ route('landads.index') }}">{{ Auth::user()->name }}</a></li>
                                  @endif
                                  <li><a href="{{ route('users.edit', $user->id) }}">Edit Profile</a></li>
                                  <li><a href="{{ route('logout') }}" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">Logout</a>
                                         <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                             {{ csrf_field() }}
                                         </form>
                                      </a>
                                  </li>
                        </ul>
                    </div>
                 </div>
                </div>
            </div>
        </header>
        <!--header-after-login-->
        @else

        <!--header-before-login-->
        <header class="before_login" style="display: block;">
            <div class="container">
                <div class="col-sm-4 logo_img">
                    <a href="{{ url('/') }}"><img src="{{ url('/public') }}/images/logo.png" class="img-responsive"></a>
                </div>
                <div class="col-sm-8 col-xs-8 userimg text-right">
                    <ul class="before_login_menu">
                        <li class="menu_link"><a href="{{ route('searchlivestocks.index') }}">Find Livestock</a></li>
                        <li class="menu_link"><a href="{{ route('searchland.index') }}">Find Land</a></li>
                        <li class="menu_link"><a href="{{ route('login') }}">Login</a></li>
                        <li class="menu_link"><a href="{{ route('register') }}">Register</a></li>
                    </ul>
                </div>
            </div>
        </header>

        <!--header-before-login-->

        @endif

<style>
.menu_after_login i{color:#000;}
.dropdown_menu_list{width:100%;}
</style>

resources/views/layouts/header2.blade.php
 <header class="">
            <div class="container-fluid">
                <div class="col-sm-4 col-xs-12 logo_img logodiv_img">
                  <a href="https://winebaa.com/" target="_blank"><img src="{{ url('/public') }}/images/winebaa_logo.png" class="img-responsive" target="_blank"></a>
                </div>
                <div class="col-sm-4 dropbaa-img text-center">
                   <a href="#" target="_blank"><img src="{{ url('/public') }}/images/dropbaa-text.png" class="dropbaa-text"><br/><img src="{{ url('/public') }}/images/dropba-logo.png" class="img-responsive dropbaaimg" target="_blank"></a>
                </div>
                <div class="col-sm-4 col-xs-12 text-right mobpadding">
                    <div class="col-sm-12">
                    @if(Auth::check())
                     <?php
                          $user = Auth::user();    
                          $user_id =  Auth::id(); 
                     ?>
                     
                     <div class="dropdown menu_after_login">
                      @if($user->profile_picture!='')
                        <button class="btn btn-primary dropdown-toggle dropdown_menu" type="button" data-toggle="dropdown"><span class="user_name_title">Welcome, {{ Auth::user()->name }}</span><img src="{{ url('/public') }}/uploads/propic/thumbnail/{{ $user->profile_picture }}" class="img-circle"></button>
                        
                      @else
                        <button class="btn btn-primary dropdown-toggle dropdown_menu" type="button" data-toggle="dropdown"><span class="user_name_title">Welcome, {{ Auth::user()->name }}</span><img src="{{ url('/public') }}/images/dummy.jpg" class="img-circle">
                        <span class="caret"></span></button>
                      @endif
                          <ul class="dropdown-menu dropdown_menu_list">
                                  @if($user->user_type == 'live_stock_owner' ) 
                                  <li><a href="{{ route('livestockads.index') }}">{{ Auth::user()->name }}</a></li>
                                  @else
                                  <li><a href="{{ route('landads.index') }}">{{ Auth::user()->name }}</a></li>
                                  @endif
                                  <li><a href="{{ route('users.edit', $user->id) }}">Edit Profile</a></li>
                                  <li><a href="{{ route('logout') }}" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">Logout</a>
                                         <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                          {{ csrf_field() }}
                                         </form>
                                      </a>
                                  </li>
                            </ul>
                       </div>
                     @else
                      <div class="col-sm-12 col-xs-12 text-right nopadding">
                        <div class="row">
                        <div class="col-sm-6 col-xs-12 col-sm-offset-6 login_btn_section">
                           <div class="btnborder">
                                <a href="{{ route('register') }}">Create Free<br/> AD </a>
                            </div>
                            <div class="btnborder">
                                <a href="{{ route('login') }}">Login</a>
                            </div>
                        </div>
                      </div>
                       @endif
                      </div>
                    </div>
                </div>
            </div>
        </header>
        <style type="text/css">
          .dropdown_menu {
              font-size: 18px;
              font-weight: bold;
          }
          .menu_after_login {
              width: auto;
          }
          .user_name_title {
              color: #708712 !important;
              padding-right: 10px;
          }
          .dropbaa-text {
    	      left: 30px;
              margin: auto;
              position: relative;
              width: 200px;
          }
	  .dropbaaimg {
    	      left: 40px;
              margin: auto;
              position: relative;
              width: 300px;
          }
          .home_leftside a {
	      border: 2px solid #000;
	      color: #000;
	      float: left;
	      font-size: 21px;
	      letter-spacing: 6px;
	      text-transform: uppercase;
	      width: 100%;
          }
	  .home_rightside a {
	      border: 2px solid #000;
	      color: #000;
	      float: left;
	      font-size: 21px;
	      letter-spacing: 6px;
	      text-transform: uppercase;
	      width: 100%;
	  }
	  .menu_after_login img {
	      padding-left: 10px;
	      width: 60px;
	  }
	  .menu_after_login .caret {
	      color: #000;
	  }
	  ul.dropdown_menu_list {
	      left: 35%;
	  }
	  @media (max-width:767px) {
	      .dropbaa-text {
	           left: 0px;
	           width: 150px;
	      }
	      .dropbaaimg {
		   left: 40px;
		   width: 150px;
	      }
          }
          .menu_after_login img {
    		height: 60px;
    		padding-left: 0px;
    		width: 60px;
	  }
        </style>
        