routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('pages.home');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('/landads','LandadsController');
Route::resource('/livestockads','LivestockadsController');
Route::resource('/searchlivestocks', 'SearchlivestockController');
Route::resource('/searchland', 'SearchlandController');
Route::get('/livestockads/{id}/edit/delete_image/{galleryid}','LivestockadsController@delete_image');
Route::get('/landads/{id}/edit/delete_image/{galleryid}','LandadsController@delete_image');
Route::resource('/users','UserController');
Route::get('/forgetpassword', 'ForgetpasswordController@index');
Route::post('/forgetpassword/send_password', 'ForgetpasswordController@send_password');

//Route::resource('/forgetpass','ForgetpasswordController');
//Route::get('/subscription/{user_id}', 'SubscriptionController@subscription');
//Route::get('/edit/{user_id}', 'UserController@edit');
//Route::get('editprofile', 'ProfileController@edit')->name('editprofile');
// Route::get('editprofile', function() {
//     return view('pages.editprofile');
// })->name('editprofile');

app/Livestockads.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Livestockads extends Model
{
   				public $fillable = [
   				 'lst_agistment_type','lst_ad_title','lst_live_stock','lst_supply_fencing','lst_payment','lst_per_head_per_week','lst_address','lst_zipcode','lst_latitude','lst_longitude','lst_pictures','lst_description',
   				];
}

app/Http/Controllers/LivestockadsController.php
<?php

namespace App\Http\Controllers;

use App\User;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Validator;
use App\Http\Requests;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Input;
use Auth;
use App\Livestockads;
use App\Post_gallery;
use Session;
use DB;
use Hash;
use Image;
use App\Classes\ErrorsClass;

class LivestockadsController extends Controller
{    

	public function __construct()
    {
        $this->middleware('auth');
    }

     public function index(Request $request)

    {   
        $user_id =  Auth::id();
        try { 

            /**** query data print *********/

                //$lastQuery = end($livestockads_user);

                //print_r($lastQuery);

            /****query data print end*****/

            $livestockads = DB::table('livestockads')
            ->where('lst_user_id', $user_id)
            ->where('status', '=', 1)
            ->where('deleted', '=', 0)
            ->orderBy('id','DESC')->paginate(10);




        return view('livestockads.index',compact('livestockads', 'livestockads_user'))

            ->with('i', ($request->input('page', 1) - 1) * 5);

        } catch (\Illuminate\Database\QueryException $e) {

            $errorClass = new ErrorsClass();
            $errors = $errorClass->saveErrors($e);

        } catch (\Exception $e) {
            $errorClass = new ErrorClass();
            $errors = $errorClass->saveErrors($e);

        } 

    }
	
	 public function create()

    {   
        try {  

    	$agistmentcats = DB::table('agistmentcat')
    						->where('status', '=', 1)
    						->where('deleted', '=', 0)
    						->orderBy('id','DESC')
    						->get();
    	$landcats = DB::table('landcat')
    						->where('status', '=', 1)
    						->where('deleted', '=', 0)
    						->orderBy('id','DESC')
    						->get();
    	$sheepcats = DB::table('sheepcat')
    						->where('status', '=', 1)
    						->where('deleted', '=', 0)
    						->orderBy('id','DESC')
    						->get();

        return view('livestockads.create',compact('agistmentcats', 'landcats', 'sheepcats'));

        } catch (\Illuminate\Database\QueryException $e) {

            $errorClass = new ErrorsClass();
            $errors = $errorClass->saveErrors($e);

        } catch (\Exception $e) {
            $errorClass = new ErrorClass();
            $errors = $errorClass->saveErrors($e);
       } 

    }
	
	    public function store(Request $request)

    {

        try {  

       /* $this->validate($request, array(

            'lst_agistment_type' => 'required|max:190',

            'lst_ad_title' => 'required|max:190',

            'lst_live_stock' => 'required|max:190',

            'lst_supply_fencing' => 'required|max:190',

            'lst_payment' => 'required|max:190',

            'lst_per_head_per_week' => 'required|max:9',

            'lst_description' => 'required|max:5000',

        ));*/
		
		$livestockad = new Livestockads;

		if(Auth::check()){
     		$user = Auth::user();    
            $user_id =  Auth::id();
		 }

		$livestockad->lst_user_id = Auth::id();
		$livestockad->lst_agistment_type = $request->lst_agistment_type;
		$livestockad->lst_ad_title = $request->lst_ad_title;
		$livestockad->lst_live_stock = implode(',',$request->lst_live_stock);
		$livestockad->lst_supply_fencing = $request->lst_supply_fencing;
		$livestockad->lst_payment = $request->lst_payment;
		$livestockad->lst_per_head_per_week = $request->lst_per_head_per_week;
        $livestockad->lst_address = $request->lst_address;
        $livestockad->lst_zipcode = $request->lst_zipcode;
		$livestockad->lst_description = $request->lst_description;
        $livestockad->created_by = Auth::id();
        $livestockad->lst_latitude = $request->lst_latitude;
        $livestockad->lst_longitude = $request->lst_longitude;
        $livestockad->save();

        $insertedId = $livestockad->id;

        if($request->hasfile('lst_pictures'))
         {
            foreach($request->file('lst_pictures') as $image )
            {
                $name = 'lndad_'. Auth::id() .'_'. time() . '.' . $image->getClientOriginalName();
                $image->move(public_path('uploads/livestockadspics/'), $name); 

                $date = date('Y-m-d H:i:s');
                
                DB::table('postgallery')->insert(
                    ['post_id' => $insertedId, 'post_type' => 'livestockads', 'file_name' => $name, 'created_by' => $user_id, 'created_at' => $date]
                    );
            }
         }

         return redirect()->route('livestockads.index')
                        ->with('success','Post created successfully');    

        } catch (\Illuminate\Database\QueryException $e) {

            $errorClass = new ErrorsClass();
            $errors = $errorClass->saveErrors($e);

        } catch (\Exception $e) {
            $errorClass = new ErrorsClass();
            $errors = $errorClass->saveErrors($e);
       }    
		             
    }
	
	public function show($id)

    {
        try {

        $livestockad = Livestockads::find($id);

        $postgalleries = DB::table('postgallery')
                            ->where('post_id', $id)
                            ->where('post_type', '=', 'livestockads')
                            ->where('status', '=', 1)
                            ->where('deleted', '=', 0)
                            ->orderBy('id','DESC')
                            ->get();


        return view('livestockads.show',compact('livestockad', 'postgalleries'));

        } catch (\Illuminate\Database\QueryException $e) {

            $errorClass = new ErrorsClass();
            $errors = $errorClass->saveErrors($e);

        } catch (\Exception $e) {
            $errorClass = new ErrorClass();
            $errors = $errorClass->saveErrors($e);
       } 
    }
	
	public function edit($id)
    {
        try { 

        $livestockad = Livestockads::find($id);

        $postgalleries = DB::table('postgallery') 
                            ->where('post_id', $id) 
                            ->where('post_type', '=', 'livestockads') 
                            ->where('status', '=', 1) 
                            ->where('deleted', '=', 0) 
                            ->orderBy('id','DESC') 
                            ->get();

        $agistmentcats = DB::table('agistmentcat')
                            ->where('status', '=', 1)
                            ->where('deleted', '=', 0)
                            ->orderBy('id','DESC')
                            ->get();

    /*	$livestockscats = DB::table('livestockscats')
                       ->where('status', '=', 1)
                       ->where('deleted', '=', 0)
                       ->orderBy('id','DESC')
                       ->get(); */

    	$sheepcats = DB::table('sheepcat')
                        ->where('status', '=', 1)
                        ->where('deleted', '=', 0)
                        ->orderBy('id','DESC')
                        ->get();
        return view('livestockads.edit',compact('livestockad','agistmentcats', 'sheepcats', 'postgalleries'));

       } catch (\Illuminate\Database\QueryException $e) {

            $errorClass = new ErrorsClass();
            $errors = $errorClass->saveErrors($e);

        } catch (\Exception $e) {
            $errorClass = new ErrorClass();
            $errors = $errorClass->saveErrors($e);
        } 

    }
	
	    public function update(Request $request, $id)
    {
        

     try{
        if(Auth::check()){
            $user = Auth::user();    
            $user_id =  Auth::id();
        }
       
        $lst_agistment_type = $request->lst_agistment_type;
        $lst_ad_title = $request->lst_ad_title;
        $lst_live_stock = implode(',',$request->lst_live_stock);
        $lst_supply_fencing = $request->lst_supply_fencing;
        $lst_payment = $request->lst_payment;
        $lst_per_head_per_week = $request->lst_per_head_per_week;
        $lst_address = $request->lst_address;
        $lst_zipcode = $request->lst_zipcode;
        $lst_description = $request->lst_description;
        $updated_by = Auth::id();
        $lst_latitude = $request->lst_latitude;
        $lst_longitude = $request->lst_longitude;

         $upQry = DB::table('livestockads')
                ->where('id', $id)
                ->update(['lst_agistment_type' => $lst_agistment_type, 'lst_ad_title' => $lst_ad_title, 'lst_live_stock' => $lst_live_stock, 'lst_supply_fencing' => $lst_supply_fencing, 'lst_payment' => $lst_payment, 'lst_per_head_per_week' => $lst_per_head_per_week, 'lst_description' => $lst_description, 'lst_address' => $lst_address, 'lst_zipcode' => $lst_zipcode, 'lst_latitude' => $lst_latitude, 'lst_longitude' => $lst_longitude, 'updated_by' => $updated_by]);


        if($request->hasfile('lst_pictures'))
         {
            foreach($request->file('lst_pictures') as $image )
            {
                $name = 'lndad_'. Auth::id() .'_'. time() . '.' . $image->getClientOriginalName();
                $image->move(public_path('uploads/livestockadspics/'), $name); 

                $date = date('Y-m-d H:i:s');
                
                DB::table('postgallery')->insert(
                    ['post_id' => $id, 'post_type' => 'livestockads', 'file_name' => $name, 'updated_by' => $user_id, 'updated_at' => $date]
                    );
            }
         }

         return redirect()->route('livestockads.index')

                        ->with('success','Post updated successfully');
		
    } catch (\Illuminate\Database\QueryException $e) {

            $errorClass = new ErrorsClass();
            $errors = $errorClass->saveErrors($e);

    } catch (\Exception $e) {
            $errorClass = new ErrorClass();
            $errors = $errorClass->saveErrors($e);
    } 

    }
	
	 public function destroy($id)
    {
        try
        {

            $livestockad = Livestockads::findOrFail($id); 

resources/views/livestockads/create.blade.php
@extends('layouts.default')

@section('title', 'Drop Baa')

@section('content')

        <div class="col-sm-8 col-sm-offset-2 formarea create_post_livestock">
          <h1>Post Your Ad</h1>
          <div class="white_bg">
          <div class="row">
          <div class="col-sm-6 col-xs-6 leftborder">
            <hr class="borderline">
          </div>
          <div class="col-sm-6 col-xs-6 rightborder">
            <hr class="borderline">
          </div>
        </div>
        <div class="registeration_section formsection">

         
          <form class="livestockadform" id="livestockadform" name="livestockadform" method="POST" action="{{ route('livestockads.store') }}" enctype="multipart/form-data">

          {{ csrf_field() }}

            <div class="row">
              <div class="col-sm-12 form-group forminput">
                <label>Agistment Type*</label>
                <select class="form-control" id="lst_agistment_type" name="lst_agistment_type">
                  <option value="">Select Your Agistment Type</option>
                  @foreach ($agistmentcats as $agistcat)
                    <option value="{{ $agistcat->id }}" {{ ( old('lst_agistment_type') ==  $agistcat->id ) ? 'selected' : '' }}>{{ $agistcat->agst_cat_name }}</option>
                  @endforeach

                </select>
              </div>
            </div>
            <div class="row">
              <div class="col-sm-12 form-group forminput">
                <label>Ad Title*</label>
                <input type="text" class="form-control" id="lst_ad_title" placeholder="Fill Your Title Here" value="{{ old('lst_ad_title') }}" name="lst_ad_title" maxlength="251">
              </div>
            </div>
                <div class="row">
                    <div class="col-sm-12 form-group forminput leftspace">
                      <label>Live Stock:*</label>
                      <div class="checkbox_div">
                        
                        @foreach ($sheepcats as $shepcat)
                        <label class="check_box">{{ $shepcat->shp_cat_name }}
                          <input type="checkbox" name="lst_live_stock[]" id="lst_live_stock_{{ $shepcat->id }}" value="{{ $shepcat->id }}"
                          {{ (is_array(old('lst_live_stock')) && in_array($shepcat->id, old('lst_live_stock'))) ? 'checked' : '' }} >
                          <span class="checkmark"></span>
                        </label>
                        @endforeach


                    </div>
                  </div>
                </div>
                     <div class="row">
              <div class="col-sm-12 form-group forminput">
                <label>Can Supply Fencing:*</label>
                <div class="col-sm-12 radiobtns nopadding">
                  <label class="radiobutton radio-inline">Yes
                  <input type="radio" name="lst_supply_fencing" id="lst_supply_fencing_1" value="Yes" {{ old('lst_supply_fencing')=="Yes" ? 'checked' : '' }}>
                  <span class="checkmark"></span>
                  </label>
                  <label class="radiobutton radio-inline">No
                  <input type="radio" name="lst_supply_fencing" id="lst_supply_fencing_2" value="No" {{ old('lst_supply_fencing')=="No" ? 'checked' : '' }}>
                  <span class="checkmark"></span>
                  </label>
                </div>
              </div>
            </div>
                      <div class="row">
              <div class="col-sm-12 form-group forminput">
                <label>Payment:*</label>
                <div class="col-sm-12 radiobtns nopadding">
                  <label class="radiobutton radio-inline">I Pay
                  <input type="radio" name="lst_payment" id="lst_payment_1" value="I-Pay" {{ old('lst_payment')=="I-Pay" ? 'checked' : '' }}>
                  <span class="checkmark"></span>
                  </label>
                  <label class="radiobutton radio-inline">They Pay
                  <input type="radio" name="lst_payment" id="lst_payment_1" value="They-Pay" {{ old('lst_payment')=="They-Pay" ? 'checked' : '' }}>
                  <span class="checkmark"></span>
                  </label>
                </div>
              </div>
            </div>
                <div class="row">
                    <div class="col-sm-12 col-xs-12 form-group forminput inputdiv currency">
                      <label>Per Head Per Week*<span>Local Currency/Tax Not Included</span></label>
                        <input type="text" class="form-control" id="lst_per_head_per_week" placeholder="$0" value="{{ old('lst_per_head_per_week') }}" name="lst_per_head_per_week" maxlength="10">
                    </div>
                </div>     
                <div class="row">
                    <div class="col-sm-12 form-group forminput">
                      <label>Address*</label>
                        <input type="text" class="form-control" id="lst_address" placeholder="Enter Address" value="{{ old('lst_address') }}" name="lst_address" maxlength="60" onfocusout="GetLocation()">
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-12 col-xs-12 form-group forminput">
                      <label>Zipcode*</label>
                        <input type="text" class="form-control" id="lst_zipcode" placeholder="Enter Zipcode" value="{{ old('lst_zipcode') }}" name="lst_zipcode" maxlength="10">
                    </div>
                </div>
            <div class="row">
              <div class="col-sm-12 form-group forminput">
                <label>Upload Sheep Images</label>
                <div class="col-sm-12 col-xs-3 browseimage nopadding" id="browse_img">
                    <img src="{{ url('/public') }}/images/default-img.png" class="img-responsive">
                </div>
                <div class="col-sm-12 col-xs-9 nopadding">
                <input type="file" id="lst_pictures" name="lst_pictures[]" multiple accept="image/*" style="display: none;">
                <div class="browse_btn" id="browsebtn">
                  <span>Select Image</span>
                  <p>No File Selected</p>
                  <p class="image_note"><strong>Note:</strong>(Please Upload images this size: 650x300 px.)</p>
                </div>
              </div>
              </div>
            </div>
              <div class="row">
              <div class="col-sm-12 form-group forminput">
                <label>Description*</label>
                <textarea class="form-control" rows="3" placeholder="Write About Sheeps" name="lst_description" id="lst_description" maxlength="5001" minlength="50">{{ old('lst_description') }}</textarea>
              </div>
            </div>

            <input type="hidden" name="lst_latitude" id="lst_latitude" value="">
            <input type="hidden" name="lst_longitude" id="lst_longitude" value="">

            <div class="savebnt text-right">
              <button type="submit" class="btn btn-default">Save</button>
            </div>
         
          </form>

        </div>
      </div>
      </div>


    <style>
      body {
            background: rgba(0, 0, 0, 0) url("{{ url('/public') }}/images/bg-img.jpg") no-repeat scroll center center / cover  ;
            height: 100vh;
          }
    </style>


<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAmECi5THi1W3CHDdmC2bI6q6dDZNRAY-I"></script>
<script type="text/javascript">
        function GetLocation() {
            var geocoder = new google.maps.Geocoder();
            var address = document.getElementById("lst_address").value;
            geocoder.geocode({ 'address': address }, function (results, status) {
                if (status == google.maps.GeocoderStatus.OK) {
                    var latitude = results[0].geometry.location.lat();
                    var longitude = results[0].geometry.location.lng();
                    $('#lst_latitude').val(latitude);
                    $('#lst_longitude').val(longitude);
                } else {
                }
            });
        };
</script>


<script>
 $(document).ready( function() {
    jQuery('#browsebtn').on('click', function() {
             jQuery('#lst_pictures').click();
       });
     
/*  jQuery("#lst_pictures").change(function() {
  var file = this.files[0];
  var imagefile = file.type;
  var imageTypes= ["image/jpeg","image/png","image/jpg"];
    if(imageTypes.indexOf(imagefile) == -1)
    {
      jQuery("#browse_img").html("<span class='msg-error'>Please Select A valid Image File</span><br /><span>Only jpeg, jpg and png Images type allowed</span>");
      return false;
    } else {
      var reader = new FileReader();
      reader.onload = function(e){
        jQuery("#browse_img").html('<img src="' + e.target.result + '"  />');        
      };
      reader.readAsDataURL(this.files[0]);
    }
  });*/

  $(function() {
    // Multiple images preview in browser
    var imagesPreview = function(input, placeToInsertImagePreview) {

        if (input.files) {
            var filesAmount = input.files.length;

            for (i = 0; i < filesAmount; i++) {
                var reader = new FileReader();

                reader.onload = function(event) {
                    $($.parseHTML('<img style="margin:0 10px">')).attr('src', event.target.result).appendTo(placeToInsertImagePreview);
                }

                reader.readAsDataURL(input.files[i]);
            }
        }

    };

    $('#lst_pictures').on('change', function() {
         jQuery('#nofile').empty(); 
          jQuery('#browse_img').empty(); 
        imagesPreview(this, '#browse_img');
    });
});

      $("#livestockadform").validate({
        ignore: [],
        rules: {
                lst_agistment_type: {
                    required: true
                },
                lst_ad_title: {
                    required: true,
                    minlength: 2,
                    maxlength: 250
                },
                'lst_live_stock[]': {
                  required: true
                },
                lst_supply_fencing: {
                    required: true
                },
                lst_payment: {
                    required: true
                },
                lst_per_head_per_week: {
                   required: true,
                   number: true,
                   maxlength: 9
                },
               lst_description: {
                   required: true,
                   maxlength: 5000
               }
            },
        messages: {
                lst_agistment_type: {
                  required: "This is required field."
                },
                lst_ad_title: {
                  required: "This is required field.",
                  minlength: "Minimum 2 characters required.",
                  maxlength: "Maximum 250 characters allowed."
                },
                'lst_live_stock[]': {
                  required: "This is required field."
                },
                lst_supply_fencing: {
                  required: "This is required field."
                },
                lst_payment: {
                  required: "This is required field."
                },
                lst_per_head_per_week: {
                  required: "This is required field.",
                  number: "Please enter a valid number.",
                  maxlength: "Maximum 9 characters allowed."
                  },
                lst_description: {
                  required: "This is required field.",
                  maxlength: "Maximum 5000 characters allowed."
                }
            },
        submitHandler: function(form) {
            form.submit();
          }
        });

 });
</script>
  @stop